"""Create a baseline migrations

Revision ID: 9af80217dcd8
Revises: 
Create Date: 2023-07-12 23:04:40.101930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af80217dcd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('norad_id', sa.Integer(), nullable=True),
    sa.Column('transaction_count', sa.String(length=200), nullable=True),
    sa.Column('tle', sa.String(length=200), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satellites')
    # ### end Alembic commands ###
